---
title: |
  Exercise 10:

  Foundations of Mathematical, WS24
author: "Zichao Wei"
date: today
abstract: |
  This is **exercise** 10 for Foundations of Mathematical, WS24.
  Generated on 2025-01-27 with 10 problems per section.
format:
  ilm-typst:
    math:
      numbering: false
      equation-prefix: ""
---

# Problems

## Vector Arithmetic

### Addition
Find the sum of the following vectors $\mathbf{u}$ and $\mathbf{v}$

1. $\mathbf{u} = \begin{bmatrix} -6 \\ 3 \\ -7 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} -3 \\ -6 \\ -5 \end{bmatrix}$ $\mathbf{u} + \mathbf{v}$.

2. $\mathbf{u} = \begin{bmatrix} -6 \\ -8 \\ 7 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 8 \\ 4 \\ 8 \end{bmatrix}$ $\mathbf{u} + \mathbf{v}$.

3. $\mathbf{u} = \begin{bmatrix} 1 \\ -8 \\ -5 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 6 \\ -4 \\ -10 \end{bmatrix}$ $\mathbf{u} + \mathbf{v}$.

4. $\mathbf{u} = \begin{bmatrix} 2 \\ -9 \\ 9 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 6 \\ -6 \\ 3 \end{bmatrix}$ $\mathbf{u} + \mathbf{v}$.

5. $\mathbf{u} = \begin{bmatrix} 10 \\ 8 \\ -6 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 1 \\ 8 \\ -5 \end{bmatrix}$ $\mathbf{u} + \mathbf{v}$.

6. $\mathbf{u} = \begin{bmatrix} -5 \\ -6 \\ 7 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 2 \\ 6 \\ 4 \end{bmatrix}$ $\mathbf{u} + \mathbf{v}$.

7. $\mathbf{u} = \begin{bmatrix} -9 \\ -5 \\ -2 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 8 \\ -6 \\ -5 \end{bmatrix}$ $\mathbf{u} + \mathbf{v}$.

8. $\mathbf{u} = \begin{bmatrix} -9 \\ -4 \\ -8 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 0 \\ -2 \\ 3 \end{bmatrix}$ $\mathbf{u} + \mathbf{v}$.

9. $\mathbf{u} = \begin{bmatrix} -2 \\ -5 \\ 9 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} -4 \\ 5 \\ -9 \end{bmatrix}$ $\mathbf{u} + \mathbf{v}$.

10. $\mathbf{u} = \begin{bmatrix} -4 \\ 1 \\ -6 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 0 \\ 7 \\ -4 \end{bmatrix}$ $\mathbf{u} + \mathbf{v}$.

### Subtraction
Find the difference of the following vectors $\mathbf{u}$ and $\mathbf{v}$

1. $\mathbf{u} = \begin{bmatrix} -2 \\ 2 \\ 5 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} -4 \\ -9 \\ -9 \end{bmatrix}$ $\mathbf{u} - \mathbf{v}$.

2. $\mathbf{u} = \begin{bmatrix} -7 \\ 9 \\ -10 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 3 \\ -4 \\ 0 \end{bmatrix}$ $\mathbf{u} - \mathbf{v}$.

3. $\mathbf{u} = \begin{bmatrix} -7 \\ -7 \\ 2 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 9 \\ -7 \\ 0 \end{bmatrix}$ $\mathbf{u} - \mathbf{v}$.

4. $\mathbf{u} = \begin{bmatrix} -7 \\ 4 \\ 8 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 0 \\ 10 \\ -10 \end{bmatrix}$ $\mathbf{u} - \mathbf{v}$.

5. $\mathbf{u} = \begin{bmatrix} -8 \\ -10 \\ 8 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} -1 \\ -5 \\ 0 \end{bmatrix}$ $\mathbf{u} - \mathbf{v}$.

6. $\mathbf{u} = \begin{bmatrix} -5 \\ -1 \\ -9 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 8 \\ 2 \\ -1 \end{bmatrix}$ $\mathbf{u} - \mathbf{v}$.

7. $\mathbf{u} = \begin{bmatrix} -6 \\ 9 \\ 1 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} -8 \\ 10 \\ -4 \end{bmatrix}$ $\mathbf{u} - \mathbf{v}$.

8. $\mathbf{u} = \begin{bmatrix} -2 \\ 9 \\ -6 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} -2 \\ 7 \\ 6 \end{bmatrix}$ $\mathbf{u} - \mathbf{v}$.

9. $\mathbf{u} = \begin{bmatrix} -1 \\ -1 \\ 5 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 7 \\ 3 \\ -6 \end{bmatrix}$ $\mathbf{u} - \mathbf{v}$.

10. $\mathbf{u} = \begin{bmatrix} 8 \\ 9 \\ -8 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} -7 \\ 8 \\ -3 \end{bmatrix}$ $\mathbf{u} - \mathbf{v}$.

### Scalar Multiplication
Find the scalar product of the following vector $\mathbf{u}$ and scalar $k$

1. $\mathbf{u} = \begin{bmatrix} 2 \\ 2 \\ -3 \end{bmatrix}$ $5\mathbf{v}$.

2. $\mathbf{u} = \begin{bmatrix} 5 \\ 9 \\ -8 \end{bmatrix}$ $2\mathbf{v}$.

3. $\mathbf{u} = \begin{bmatrix} -7 \\ 2 \\ -6 \end{bmatrix}$ $4\mathbf{v}$.

4. $\mathbf{u} = \begin{bmatrix} -3 \\ -1 \\ 1 \end{bmatrix}$ $7\mathbf{v}$.

5. $\mathbf{u} = \begin{bmatrix} 10 \\ 1 \\ 2 \end{bmatrix}$ $6\mathbf{v}$.

6. $\mathbf{u} = \begin{bmatrix} 7 \\ 0 \\ 6 \end{bmatrix}$ $1\mathbf{v}$.

7. $\mathbf{u} = \begin{bmatrix} -1 \\ -4 \\ 10 \end{bmatrix}$ $0\mathbf{v}$.

8. $\mathbf{u} = \begin{bmatrix} -9 \\ -10 \\ 7 \end{bmatrix}$ $-3\mathbf{v}$.

9. $\mathbf{u} = \begin{bmatrix} -3 \\ -1 \\ -7 \end{bmatrix}$ $10\mathbf{v}$.

10. $\mathbf{u} = \begin{bmatrix} 2 \\ -6 \\ -4 \end{bmatrix}$ $3\mathbf{v}$.

## Matrix Arithmetic

### Addition
Find the sum of the following matrices $A$ and $B$

1. $$A = \begin{bmatrix} -5 & 1 & -2 \\ 3 & 0 & -3 \\ 5 & 8 & 1 \end{bmatrix}$$ and $$B = \begin{bmatrix} -4 & -6 & 2 \\ 0 & -4 & 9 \\ 2 & 2 & -7 \end{bmatrix}$$

2. $$A = \begin{bmatrix} -8 & -5 & -1 \\ -5 & 2 & 5 \\ -3 & -8 & -9 \end{bmatrix}$$ and $$B = \begin{bmatrix} -8 & 4 & 1 \\ 7 & 7 & -1 \\ 4 & -7 & -8 \end{bmatrix}$$

3. $$A = \begin{bmatrix} -10 & -10 & -1 \\ 3 & -2 & -6 \\ -8 & 9 & -4 \end{bmatrix}$$ and $$B = \begin{bmatrix} -6 & 2 & 9 \\ 6 & -9 & -7 \\ -10 & -4 & 3 \end{bmatrix}$$

4. $$A = \begin{bmatrix} 7 & -5 & -2 \\ -7 & 9 & -1 \\ 4 & 1 & 1 \end{bmatrix}$$ and $$B = \begin{bmatrix} 0 & 9 & 0 \\ -1 & 1 & 2 \\ -9 & -4 & -8 \end{bmatrix}$$

5. $$A = \begin{bmatrix} 0 & -4 & 3 \\ -10 & -10 & 9 \\ 8 & -5 & 0 \end{bmatrix}$$ and $$B = \begin{bmatrix} 1 & -5 & -7 \\ 5 & -6 & 1 \\ -8 & -6 & 8 \end{bmatrix}$$

6. $$A = \begin{bmatrix} 2 & 1 & 2 \\ -4 & -1 & 6 \\ -3 & -7 & -2 \end{bmatrix}$$ and $$B = \begin{bmatrix} -6 & 3 & 8 \\ -5 & -8 & 0 \\ 1 & -2 & -2 \end{bmatrix}$$

7. $$A = \begin{bmatrix} -4 & 2 & 2 \\ 3 & 9 & 9 \\ -9 & 1 & -2 \end{bmatrix}$$ and $$B = \begin{bmatrix} 8 & 2 & 7 \\ 7 & 5 & 3 \\ -6 & -8 & -9 \end{bmatrix}$$

8. $$A = \begin{bmatrix} -3 & 0 & -3 \\ -1 & -9 & -8 \\ -6 & 7 & 2 \end{bmatrix}$$ and $$B = \begin{bmatrix} 6 & -4 & 3 \\ -3 & -9 & 6 \\ 7 & 7 & -5 \end{bmatrix}$$

9. $$A = \begin{bmatrix} -5 & -1 & -4 \\ 2 & -8 & 5 \\ 4 & -2 & 3 \end{bmatrix}$$ and $$B = \begin{bmatrix} -9 & -6 & 6 \\ 3 & -1 & -2 \\ -10 & -4 & -8 \end{bmatrix}$$

10. $$A = \begin{bmatrix} -10 & -3 & -2 \\ 7 & -8 & -10 \\ -5 & 0 & 5 \end{bmatrix}$$ and $$B = \begin{bmatrix} -5 & -3 & -4 \\ -5 & 0 & 1 \\ 6 & -2 & -6 \end{bmatrix}$$

### Subtraction
Find the difference of the following matrices $A$ and $B$

1. $$A = \begin{bmatrix} 6 & -5 & 1 \\ 3 & 4 & 3 \\ 9 & -1 & -2 \end{bmatrix}$$ and $$B = \begin{bmatrix} -10 & 5 & -8 \\ 7 & -1 & 7 \\ 0 & 5 & -4 \end{bmatrix}$$

2. $$A = \begin{bmatrix} 0 & -8 & 6 \\ -10 & 5 & 4 \\ 8 & 2 & -3 \end{bmatrix}$$ and $$B = \begin{bmatrix} 4 & -10 & 6 \\ -9 & 3 & -3 \\ 2 & 4 & -5 \end{bmatrix}$$

3. $$A = \begin{bmatrix} -4 & -8 & -1 \\ 8 & 6 & 6 \\ 6 & -4 & 2 \end{bmatrix}$$ and $$B = \begin{bmatrix} 3 & 0 & -8 \\ 4 & -4 & -1 \\ -6 & -3 & -6 \end{bmatrix}$$

4. $$A = \begin{bmatrix} -7 & -3 & -1 \\ 9 & 3 & 0 \\ 9 & 5 & -4 \end{bmatrix}$$ and $$B = \begin{bmatrix} -10 & -3 & -5 \\ -5 & -7 & -7 \\ -2 & -1 & -10 \end{bmatrix}$$

5. $$A = \begin{bmatrix} 9 & 7 & -3 \\ -8 & -9 & 3 \\ -1 & -4 & 4 \end{bmatrix}$$ and $$B = \begin{bmatrix} 7 & 9 & 1 \\ 6 & 1 & 8 \\ -6 & 1 & 4 \end{bmatrix}$$

6. $$A = \begin{bmatrix} -6 & -8 & -3 \\ -3 & 1 & -6 \\ -5 & -10 & -9 \end{bmatrix}$$ and $$B = \begin{bmatrix} -4 & 7 & 5 \\ 2 & 4 & -2 \\ -5 & 8 & 4 \end{bmatrix}$$

7. $$A = \begin{bmatrix} 7 & -5 & 2 \\ 4 & -4 & -6 \\ -5 & 7 & -8 \end{bmatrix}$$ and $$B = \begin{bmatrix} -5 & 1 & 8 \\ -4 & 9 & -5 \\ 0 & 1 & 1 \end{bmatrix}$$

8. $$A = \begin{bmatrix} 1 & 5 & 0 \\ -7 & 8 & -5 \\ -10 & 0 & 8 \end{bmatrix}$$ and $$B = \begin{bmatrix} -9 & 1 & 1 \\ -3 & 3 & 9 \\ 9 & -6 & 5 \end{bmatrix}$$

9. $$A = \begin{bmatrix} 5 & -6 & 5 \\ -3 & -6 & -7 \\ -10 & -1 & 6 \end{bmatrix}$$ and $$B = \begin{bmatrix} -6 & -9 & -1 \\ -10 & 9 & -9 \\ 4 & -6 & -10 \end{bmatrix}$$

10. $$A = \begin{bmatrix} 9 & 1 & 6 \\ -8 & -2 & -8 \\ 2 & -3 & 4 \end{bmatrix}$$ and $$B = \begin{bmatrix} 0 & 1 & 8 \\ 6 & -8 & -4 \\ 1 & 5 & 4 \end{bmatrix}$$

### Multiplication
Find the product of the following matrices $A$ and $B$

1. $$A = \begin{bmatrix} 7 & 3 & 0 \\ 7 & 6 & -5 \\ 9 & 0 & -1 \end{bmatrix}$$ and $$B = \begin{bmatrix} 1 & -8 & -8 \\ -2 & -2 & -2 \\ 6 & -7 & 7 \end{bmatrix}$$

2. $$A = \begin{bmatrix} -6 & 8 & -9 \\ -6 & 4 & -8 \\ -8 & 5 & -9 \end{bmatrix}$$ and $$B = \begin{bmatrix} 7 & -3 & 2 \\ -4 & -8 & 1 \\ -9 & -2 & 7 \end{bmatrix}$$

3. $$A = \begin{bmatrix} 9 & -1 & 5 \\ 0 & 2 & 8 \\ -7 & 5 & 6 \end{bmatrix}$$ and $$B = \begin{bmatrix} 2 & 5 & -9 \\ -9 & 5 & -1 \\ 7 & 7 & 3 \end{bmatrix}$$

4. $$A = \begin{bmatrix} -9 & -7 & -1 \\ 1 & -10 & -1 \\ 8 & 2 & 8 \end{bmatrix}$$ and $$B = \begin{bmatrix} 4 & -3 & 0 \\ 9 & -6 & -5 \\ 7 & 9 & -7 \end{bmatrix}$$

5. $$A = \begin{bmatrix} 0 & 3 & 9 \\ 0 & -2 & 4 \\ -3 & -5 & -8 \end{bmatrix}$$ and $$B = \begin{bmatrix} 7 & 6 & 8 \\ 1 & 1 & 9 \\ -9 & 8 & 8 \end{bmatrix}$$

6. $$A = \begin{bmatrix} 0 & -1 & -9 \\ 0 & -4 & 9 \\ -10 & -6 & -2 \end{bmatrix}$$ and $$B = \begin{bmatrix} 2 & -7 & 5 \\ 6 & 7 & 1 \\ 9 & -8 & 4 \end{bmatrix}$$

7. $$A = \begin{bmatrix} 7 & 9 & -5 \\ -5 & -5 & -6 \\ -9 & -5 & -3 \end{bmatrix}$$ and $$B = \begin{bmatrix} -5 & -9 & 0 \\ -2 & -1 & 7 \\ -4 & 6 & -4 \end{bmatrix}$$

8. $$A = \begin{bmatrix} 6 & 6 & -3 \\ -2 & -1 & -3 \\ -3 & 6 & -1 \end{bmatrix}$$ and $$B = \begin{bmatrix} 7 & -8 & 9 \\ -4 & 2 & -5 \\ -6 & -3 & 3 \end{bmatrix}$$

9. $$A = \begin{bmatrix} 3 & 9 & 4 \\ -9 & -8 & 4 \\ 0 & 7 & 8 \end{bmatrix}$$ and $$B = \begin{bmatrix} -10 & 8 & -10 \\ 8 & -4 & -1 \\ -3 & -4 & -5 \end{bmatrix}$$

10. $$A = \begin{bmatrix} 2 & -2 & -2 \\ -6 & -3 & -6 \\ -2 & -2 & -9 \end{bmatrix}$$ and $$B = \begin{bmatrix} 3 & 2 & 7 \\ -4 & 5 & -5 \\ 3 & 9 & 0 \end{bmatrix}$$

## Matrix Properties

### Properties
For each matrix $A$, find:

a) rank($A$)

b) nullity($A$)

c) det($A$)

d) $A^{-1}$ (if exists)

e) basis of ker($A$)

1. $$A = \begin{bmatrix} 3 & 1 & -4 \\ -4 & -1 & 5 \\ 3 & 1 & -4 \end{bmatrix}$$

2. $$A = \begin{bmatrix} -1 & 3 & 2 \\ -1 & 2 & 1 \\ -1 & 1 & 0 \end{bmatrix}$$

3. $$A = \begin{bmatrix} 3 & 3 & 3 \\ -1 & 0 & 0 \\ -1 & -1 & -1 \end{bmatrix}$$

4. $$A = \begin{bmatrix} 3 & -7 & 7 \\ 0 & 1 & -1 \\ 2 & -6 & 6 \end{bmatrix}$$

5. $$A = \begin{bmatrix} 1 & -1 & 0 \\ 1 & 0 & -1 \\ 0 & 0 & 0 \end{bmatrix}$$

6. $$A = \begin{bmatrix} 3 & -2 & -7 \\ 2 & -1 & -5 \\ -2 & 2 & 4 \end{bmatrix}$$

7. $$A = \begin{bmatrix} 1 & -1 & -5 \\ 0 & 1 & -1 \\ 0 & 0 & 1 \end{bmatrix}$$

8. $$A = \begin{bmatrix} 1 & 2 & -1 \\ -2 & -1 & 5 \\ 0 & 2 & 2 \end{bmatrix}$$

9. $$A = \begin{bmatrix} -1 & 0 & 0 \\ 1 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$

10. $$A = \begin{bmatrix} 2 & 1 & -10 \\ 1 & 1 & -6 \\ 0 & 0 & 1 \end{bmatrix}$$

### RREF
Find the Reduced Row Echelon Form of the following matrix $A$

1. $$A = \begin{bmatrix} 2 & 1 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$

2. $$A = \begin{bmatrix} 1 & 0 & 2 \\ -6 & -3 & -14 \\ 4 & 2 & 9 \end{bmatrix}$$

3. $$A = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$$

4. $$A = \begin{bmatrix} 1 & -2 & 0 \\ 0 & 0 & 0 \\ 0 & 1 & -2 \end{bmatrix}$$

5. $$A = \begin{bmatrix} 1 & 0 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$$

6. $$A = \begin{bmatrix} 1 & -1 & 0 \\ -2 & 3 & 0 \\ 0 & 0 & 0 \end{bmatrix}$$

7. $$A = \begin{bmatrix} 1 & 0 & 3 \\ 0 & 1 & -2 \\ 0 & 0 & 1 \end{bmatrix}$$

8. $$A = \begin{bmatrix} 5 & -8 & 0 \\ 2 & -3 & 0 \\ 2 & -3 & 0 \end{bmatrix}$$

9. $$A = \begin{bmatrix} 3 & -2 & 0 \\ -1 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$

10. $$A = \begin{bmatrix} 1 & 0 & -1 \\ 1 & 1 & -1 \\ -1 & 0 & 1 \end{bmatrix}$$

## Calculus

### Limit
Calculate the following limits

1. Calculate the limit of the following expression: $$\lim_{x \to 0} \frac{\log{\left(x + 1 \right)}}{x}$$

2. Calculate the limit of the following expression: $$\lim_{x \to 1} \frac{x^{2} - 1}{x - 1}$$

3. Calculate the limit of the following expression: $$\lim_{x \to 0} \frac{\log{\left(x + 1 \right)}}{x}$$

4. Calculate the limit of the following expression: $$\lim_{x \to -3} -2$$

5. Calculate the limit of the following expression: $$\lim_{x \to 0} \frac{\log{\left(x + 1 \right)}}{x}$$

6. Calculate the limit of the following expression: $$\lim_{x \to 0} \frac{\log{\left(x + 1 \right)}}{x}$$

7. Calculate the limit of the following expression: $$\lim_{x \to 0} \frac{\log{\left(x + 1 \right)}}{x}$$

8. Calculate the limit of the following expression: $$\lim_{x \to 3} 3 x^{3} + 4 x^{2} - 4 x - 1$$

9. Calculate the limit of the following expression: $$\lim_{x \to 1} \frac{x^{2} - 1}{x - 1}$$

10. Calculate the limit of the following expression: $$\lim_{x \to 1} 3 x^{2} + 4 x + 4$$

### Derivative
Calculate the derivatives of the following expressions

1. Calculate the derivative of the following expression: $$\log{\left(x + 1 \right)} + \log{\left(x^{2} + 1 \right)}$$

2. Calculate the derivative of the following expression: $$\log{\left(x \right)}$$

3. Calculate the derivative of the following expression: $$e^{2 x} + e^{x^{2}}$$

4. Calculate the derivative of the following expression: $$\log{\left(x + 1 \right)} + \log{\left(x^{2} + 1 \right)}$$

5. Calculate the derivative of the following expression: $$x^{2} e^{x}$$

6. Calculate the derivative of the following expression: $$e^{2 x} + e^{x^{2}}$$

7. Calculate the derivative of the following expression: $$e^{x}$$

8. Calculate the derivative of the following expression: $$x^{3} e^{x}$$

9. Calculate the derivative of the following expression: $$\frac{x^{2}}{x^{2} + 1}$$

10. Calculate the derivative of the following expression: $$\log{\left(x + 1 \right)} + \log{\left(x^{2} + 1 \right)}$$

### Integral
Calculate the indefinite and definite integrals of the following expressions

1. the indefinite integral and evaluate from 2 to 3:
$$\int \sqrt{4 - x^{2}} dx$$

2. the indefinite integral and evaluate from 2 to 5:
$$\int e^{- x^{2}} dx$$

3. the indefinite integral and evaluate from 2 to 2:
$$\int e^{- x^{2}} dx$$

4. the indefinite integral and evaluate from 1 to 3:
$$\int e^{x} \sin{\left(x \right)} dx$$

5. the indefinite integral and evaluate from 2 to 3:
$$\int \frac{x}{x^{2} - 5 x + 6} dx$$

6. the indefinite integral and evaluate from 4 to 4:
$$\int \frac{1}{x \log{\left(x \right)}} dx$$

7. the indefinite integral and evaluate from 1 to 3:
$$\int x^{4} + 5 x^{3} + 5 x^{2} + x + 3 dx$$

8. the indefinite integral and evaluate from 2 to 4:
$$\int x^{3} \log{\left(x \right)} dx$$

9. the indefinite integral and evaluate from 3 to 4:
$$\int \frac{1}{x^{2} + 1} dx$$

10. the indefinite integral and evaluate from 4 to 5:
$$\int \sqrt{4 - x^{2}} dx$$

### Partial Derivative
Calculate the partial derivatives of the following expressions

1. the partial derivatives of the function:
$$f(x,y) = x^{3} y^{2} - 3 x^{2} y + 2 x y^{3}$$
 $\frac{\partial f}{\partial x}$ and $\frac{\partial f}{\partial y}$

2. the second order partial derivative of:
$$f(x,y) = x^{4} y^{3} + 3 x^{2} y^{4}$$
 $\frac{\partial^2 f}{\partial x^2}$

3. the partial derivatives of the function:
$$f(x,y) = \left(x + y\right) e^{x^{2} + y^{2}}$$
 $\frac{\partial f}{\partial x}$ and $\frac{\partial f}{\partial y}$

4. the mixed partial derivative of:
$$f(x,y) = x^{3} y^{2} + x y^{4}$$
 $\frac{\partial^2 f}{\partial x \partial y}$

5. the partial derivatives of the function:
$$f(x,y) = \left(x + y\right) e^{x^{2} + y^{2}}$$
 $\frac{\partial f}{\partial x}$ and $\frac{\partial f}{\partial y}$

6. the partial derivatives of the function:
$$f(x,y) = \left(x + y\right) e^{x^{2} + y^{2}}$$
 $\frac{\partial f}{\partial x}$ and $\frac{\partial f}{\partial y}$

7. the partial derivatives of the function:
$$f(x,y) = \left(x + y\right) e^{x^{2} + y^{2}}$$
 $\frac{\partial f}{\partial x}$ and $\frac{\partial f}{\partial y}$

8. Given the implicit function:
$$x^{2} y + x y^{2} - x y = 0$$
 $\frac{\partial y}{\partial x}$

9. the partial derivatives of the function:
$$f(x,y) = \left(x + y\right) e^{x^{2} + y^{2}}$$
 $\frac{\partial f}{\partial x}$ and $\frac{\partial f}{\partial y}$

10. Given the implicit function:
$$x^{2} y + x y^{2} - x y = 0$$
 $\frac{\partial y}{\partial x}$


# Solutions

## Vector Arithmetic

### Addition

$\begin{bmatrix} -9 \\ -3 \\ -12 \end{bmatrix}$ $\begin{bmatrix} 2 \\ -4 \\ 15 \end{bmatrix}$ $\begin{bmatrix} 7 \\ -12 \\ -15 \end{bmatrix}$ $\begin{bmatrix} 8 \\ -15 \\ 12 \end{bmatrix}$ $\begin{bmatrix} 11 \\ 16 \\ -11 \end{bmatrix}$

$\begin{bmatrix} -3 \\ 0 \\ 11 \end{bmatrix}$ $\begin{bmatrix} -1 \\ -11 \\ -7 \end{bmatrix}$ $\begin{bmatrix} -9 \\ -6 \\ -5 \end{bmatrix}$ $\begin{bmatrix} -6 \\ 0 \\ 0 \end{bmatrix}$ $\begin{bmatrix} -4 \\ 8 \\ -10 \end{bmatrix}$

### Subtraction

$\begin{bmatrix} 2 \\ 11 \\ 14 \end{bmatrix}$ $\begin{bmatrix} -10 \\ 13 \\ -10 \end{bmatrix}$ $\begin{bmatrix} -16 \\ 0 \\ 2 \end{bmatrix}$ $\begin{bmatrix} -7 \\ -6 \\ 18 \end{bmatrix}$ $\begin{bmatrix} -7 \\ -5 \\ 8 \end{bmatrix}$

$\begin{bmatrix} -13 \\ -3 \\ -8 \end{bmatrix}$ $\begin{bmatrix} 2 \\ -1 \\ 5 \end{bmatrix}$ $\begin{bmatrix} 0 \\ 2 \\ -12 \end{bmatrix}$ $\begin{bmatrix} -8 \\ -4 \\ 11 \end{bmatrix}$ $\begin{bmatrix} 15 \\ 1 \\ -5 \end{bmatrix}$

### Scalar Multiplication

1: $\begin{bmatrix} 10 \\ 10 \\ -15 \end{bmatrix}$ 2: $\begin{bmatrix} 10 \\ 18 \\ -16 \end{bmatrix}$ 3: $\begin{bmatrix} -28 \\ 8 \\ -24 \end{bmatrix}$ 4: $\begin{bmatrix} -21 \\ -7 \\ 7 \end{bmatrix}$ 5: $\begin{bmatrix} 60 \\ 6 \\ 12 \end{bmatrix}$

6: $\begin{bmatrix} 7 \\ 0 \\ 6 \end{bmatrix}$ 7: $\begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}$ 8: $\begin{bmatrix} 27 \\ 30 \\ -21 \end{bmatrix}$ 9: $\begin{bmatrix} -30 \\ -10 \\ -70 \end{bmatrix}$ 10: $\begin{bmatrix} 6 \\ -18 \\ -12 \end{bmatrix}$

## Matrix Arithmetic

### Addition

1: $$\begin{bmatrix} -9 & -5 & 0 \\ 3 & -4 & 6 \\ 7 & 10 & -6 \end{bmatrix}$$ 1: $$\begin{bmatrix} -16 & -1 & 0 \\ 2 & 9 & 4 \\ 1 & -15 & -17 \end{bmatrix}$$ 1: $$\begin{bmatrix} -16 & -8 & 8 \\ 9 & -11 & -13 \\ -18 & 5 & -1 \end{bmatrix}$$ 1: $$\begin{bmatrix} 7 & 4 & -2 \\ -8 & 10 & 1 \\ -5 & -3 & -7 \end{bmatrix}$$ 1: $$\begin{bmatrix} 1 & -9 & -4 \\ -5 & -16 & 10 \\ 0 & -11 & 8 \end{bmatrix}$$

1: $$\begin{bmatrix} -4 & 4 & 10 \\ -9 & -9 & 6 \\ -2 & -9 & -4 \end{bmatrix}$$ 1: $$\begin{bmatrix} 4 & 4 & 9 \\ 10 & 14 & 12 \\ -15 & -7 & -11 \end{bmatrix}$$ 1: $$\begin{bmatrix} 3 & -4 & 0 \\ -4 & -18 & -2 \\ 1 & 14 & -3 \end{bmatrix}$$ 1: $$\begin{bmatrix} -14 & -7 & 2 \\ 5 & -9 & 3 \\ -6 & -6 & -5 \end{bmatrix}$$ 1: $$\begin{bmatrix} -15 & -6 & -6 \\ 2 & -8 & -9 \\ 1 & -2 & -1 \end{bmatrix}$$

### Subtraction

1: $$\begin{bmatrix} 16 & -10 & 9 \\ -4 & 5 & -4 \\ 9 & -6 & 2 \end{bmatrix}$$ 1: $$\begin{bmatrix} -4 & 2 & 0 \\ -1 & 2 & 7 \\ 6 & -2 & 2 \end{bmatrix}$$ 1: $$\begin{bmatrix} -7 & -8 & 7 \\ 4 & 10 & 7 \\ 12 & -1 & 8 \end{bmatrix}$$ 1: $$\begin{bmatrix} 3 & 0 & 4 \\ 14 & 10 & 7 \\ 11 & 6 & 6 \end{bmatrix}$$ 1: $$\begin{bmatrix} 2 & -2 & -4 \\ -14 & -10 & -5 \\ 5 & -5 & 0 \end{bmatrix}$$

1: $$\begin{bmatrix} -2 & -15 & -8 \\ -5 & -3 & -4 \\ 0 & -18 & -13 \end{bmatrix}$$ 1: $$\begin{bmatrix} 12 & -6 & -6 \\ 8 & -13 & -1 \\ -5 & 6 & -9 \end{bmatrix}$$ 1: $$\begin{bmatrix} 10 & 4 & -1 \\ -4 & 5 & -14 \\ -19 & 6 & 3 \end{bmatrix}$$ 1: $$\begin{bmatrix} 11 & 3 & 6 \\ 7 & -15 & 2 \\ -14 & 5 & 16 \end{bmatrix}$$ 1: $$\begin{bmatrix} 9 & 0 & -2 \\ -14 & 6 & -4 \\ 1 & -8 & 0 \end{bmatrix}$$

### Multiplication

1: $$\begin{bmatrix} 1 & -62 & -62 \\ -35 & -33 & -103 \\ 3 & -65 & -79 \end{bmatrix}$$ 1: $$\begin{bmatrix} 7 & -28 & -67 \\ 14 & 2 & -64 \\ 5 & 2 & -74 \end{bmatrix}$$ 1: $$\begin{bmatrix} 62 & 75 & -65 \\ 38 & 66 & 22 \\ -17 & 32 & 76 \end{bmatrix}$$ 1: $$\begin{bmatrix} -106 & 60 & 42 \\ -93 & 48 & 57 \\ 106 & 36 & -66 \end{bmatrix}$$ 1: $$\begin{bmatrix} -78 & 75 & 99 \\ -38 & 30 & 14 \\ 46 & -87 & -133 \end{bmatrix}$$

1: $$\begin{bmatrix} -87 & 65 & -37 \\ 57 & -100 & 32 \\ -74 & 44 & -64 \end{bmatrix}$$ 1: $$\begin{bmatrix} -33 & -102 & 83 \\ 59 & 14 & -11 \\ 67 & 68 & -23 \end{bmatrix}$$ 1: $$\begin{bmatrix} 36 & -27 & 15 \\ 8 & 23 & -22 \\ -39 & 39 & -60 \end{bmatrix}$$ 1: $$\begin{bmatrix} 30 & -28 & -59 \\ 14 & -56 & 78 \\ 32 & -60 & -47 \end{bmatrix}$$ 1: $$\begin{bmatrix} 8 & -24 & 24 \\ -24 & -81 & -27 \\ -25 & -95 & -4 \end{bmatrix}$$

## Matrix Properties

### Properties

**Solution**

**Row Operations:**

Step 1: $r_1 := 1/3r_1$
$\begin{bmatrix} 1 & 1/3 & -4/3 & | & 1/3 & 0 & 0 \\ -4 & -1 & 5 & | & 0 & 1 & 0 \\ 3 & 1 & -4 & | & 0 & 0 & 1 \end{bmatrix}$

Step 2: $r_2 := r_2 - (-4)r_1$
$\begin{bmatrix} 1 & 1/3 & -4/3 & | & 1/3 & 0 & 0 \\ 0 & 1/3 & -1/3 & | & 4/3 & 1 & 0 \\ 3 & 1 & -4 & | & 0 & 0 & 1 \end{bmatrix}$

Step 3: $r_3 := r_3 - (3)r_1$
$\begin{bmatrix} 1 & 1/3 & -4/3 & | & 1/3 & 0 & 0 \\ 0 & 1/3 & -1/3 & | & 4/3 & 1 & 0 \\ 0 & 0 & 0 & | & -1 & 0 & 1 \end{bmatrix}$

Step 4: $r_2 := 3r_2$
$\begin{bmatrix} 1 & 1/3 & -4/3 & | & 1/3 & 0 & 0 \\ 0 & 1 & -1 & | & 4 & 3 & 0 \\ 0 & 0 & 0 & | & -1 & 0 & 1 \end{bmatrix}$

Step 5: $r_1 := r_1 - (1/3)r_2$
$\begin{bmatrix} 1 & 0 & -1 & | & -1 & -1 & 0 \\ 0 & 1 & -1 & | & 4 & 3 & 0 \\ 0 & 0 & 0 & | & -1 & 0 & 1 \end{bmatrix}$

**Results:**

a) rank($A$) = 2

b) nullity($A$) = 1

c) det($A$) = 0

d) $A^{-1} = \text{does not exist}$

e) ker($A$) = $\text{span}\left\{\begin{bmatrix} 2 \\ 1 \\ 1 \end{bmatrix}\right\}$

 **Solution**

**Row Operations:**

Step 1: $r_1 := -1r_1$
$\begin{bmatrix} 1 & -3 & -2 & | & -1 & 0 & 0 \\ -1 & 2 & 1 & | & 0 & 1 & 0 \\ -1 & 1 & 0 & | & 0 & 0 & 1 \end{bmatrix}$

Step 2: $r_2 := r_2 - (-1)r_1$
$\begin{bmatrix} 1 & -3 & -2 & | & -1 & 0 & 0 \\ 0 & -1 & -1 & | & -1 & 1 & 0 \\ -1 & 1 & 0 & | & 0 & 0 & 1 \end{bmatrix}$

Step 3: $r_3 := r_3 - (-1)r_1$
$\begin{bmatrix} 1 & -3 & -2 & | & -1 & 0 & 0 \\ 0 & -1 & -1 & | & -1 & 1 & 0 \\ 0 & -2 & -2 & | & -1 & 0 & 1 \end{bmatrix}$

Step 4: $r_2 := -1r_2$
$\begin{bmatrix} 1 & -3 & -2 & | & -1 & 0 & 0 \\ 0 & 1 & 1 & | & 1 & -1 & 0 \\ 0 & -2 & -2 & | & -1 & 0 & 1 \end{bmatrix}$

Step 5: $r_1 := r_1 - (-3)r_2$
$\begin{bmatrix} 1 & 0 & 1 & | & 2 & -3 & 0 \\ 0 & 1 & 1 & | & 1 & -1 & 0 \\ 0 & -2 & -2 & | & -1 & 0 & 1 \end{bmatrix}$

Step 6: $r_3 := r_3 - (-2)r_2$
$\begin{bmatrix} 1 & 0 & 1 & | & 2 & -3 & 0 \\ 0 & 1 & 1 & | & 1 & -1 & 0 \\ 0 & 0 & 0 & | & 1 & -2 & 1 \end{bmatrix}$

**Results:**

a) rank($A$) = 2

b) nullity($A$) = 1

c) det($A$) = 0

d) $A^{-1} = \text{does not exist}$

e) ker($A$) = $\text{span}\left\{\begin{bmatrix} 0 \\ -1 \\ 1 \end{bmatrix}\right\}$

 **Solution**

**Row Operations:**

Step 1: $r_1 := 1/3r_1$
$\begin{bmatrix} 1 & 1 & 1 & | & 1/3 & 0 & 0 \\ -1 & 0 & 0 & | & 0 & 1 & 0 \\ -1 & -1 & -1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 2: $r_2 := r_2 - (-1)r_1$
$\begin{bmatrix} 1 & 1 & 1 & | & 1/3 & 0 & 0 \\ 0 & 1 & 1 & | & 1/3 & 1 & 0 \\ -1 & -1 & -1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 3: $r_3 := r_3 - (-1)r_1$
$\begin{bmatrix} 1 & 1 & 1 & | & 1/3 & 0 & 0 \\ 0 & 1 & 1 & | & 1/3 & 1 & 0 \\ 0 & 0 & 0 & | & 1/3 & 0 & 1 \end{bmatrix}$

Step 4: $r_1 := r_1 - r_2$
$\begin{bmatrix} 1 & 0 & 0 & | & 0 & -1 & 0 \\ 0 & 1 & 1 & | & 1/3 & 1 & 0 \\ 0 & 0 & 0 & | & 1/3 & 0 & 1 \end{bmatrix}$

**Results:**

a) rank($A$) = 2

b) nullity($A$) = 1

c) det($A$) = 0

d) $A^{-1} = \text{does not exist}$

e) ker($A$) = $\text{span}\left\{\begin{bmatrix} -1 \\ -1 \\ 1 \end{bmatrix}\right\}$

 **Solution**

**Row Operations:**

Step 1: $r_1 := 1/3r_1$
$\begin{bmatrix} 1 & -7/3 & 7/3 & | & 1/3 & 0 & 0 \\ 0 & 1 & -1 & | & 0 & 1 & 0 \\ 2 & -6 & 6 & | & 0 & 0 & 1 \end{bmatrix}$

Step 2: $r_3 := r_3 - (2)r_1$
$\begin{bmatrix} 1 & -7/3 & 7/3 & | & 1/3 & 0 & 0 \\ 0 & 1 & -1 & | & 0 & 1 & 0 \\ 0 & -4/3 & 4/3 & | & -2/3 & 0 & 1 \end{bmatrix}$

Step 3: $r_1 := r_1 - (-7/3)r_2$
$\begin{bmatrix} 1 & 0 & 0 & | & 1/3 & 7/3 & 0 \\ 0 & 1 & -1 & | & 0 & 1 & 0 \\ 0 & -4/3 & 4/3 & | & -2/3 & 0 & 1 \end{bmatrix}$

Step 4: $r_3 := r_3 - (-4/3)r_2$
$\begin{bmatrix} 1 & 0 & 0 & | & 1/3 & 7/3 & 0 \\ 0 & 1 & -1 & | & 0 & 1 & 0 \\ 0 & 0 & 0 & | & -2/3 & 4/3 & 1 \end{bmatrix}$

**Results:**

a) rank($A$) = 2

b) nullity($A$) = 1

c) det($A$) = 0

d) $A^{-1} = \text{does not exist}$

e) ker($A$) = $\text{span}\left\{\begin{bmatrix} -2 \\ 1 \\ 1 \end{bmatrix}\right\}$

 **Solution**

**Row Operations:**

Step 1: $r_2 := r_2 - r_1$
$\begin{bmatrix} 1 & -1 & 0 & | & 1 & 0 & 0 \\ 0 & 1 & -1 & | & -1 & 1 & 0 \\ 0 & 0 & 0 & | & 0 & 0 & 1 \end{bmatrix}$

Step 2: $r_1 := r_1 - (-1)r_2$
$\begin{bmatrix} 1 & 0 & -1 & | & 0 & 1 & 0 \\ 0 & 1 & -1 & | & -1 & 1 & 0 \\ 0 & 0 & 0 & | & 0 & 0 & 1 \end{bmatrix}$

**Results:**

a) rank($A$) = 2

b) nullity($A$) = 1

c) det($A$) = 0

d) $A^{-1} = \text{does not exist}$

e) ker($A$) = $\text{span}\left\{\begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\right\}$



**Solution**

**Row Operations:**

Step 1: $r_1 := 1/3r_1$
$\begin{bmatrix} 1 & -2/3 & -7/3 & | & 1/3 & 0 & 0 \\ 2 & -1 & -5 & | & 0 & 1 & 0 \\ -2 & 2 & 4 & | & 0 & 0 & 1 \end{bmatrix}$

Step 2: $r_2 := r_2 - (2)r_1$
$\begin{bmatrix} 1 & -2/3 & -7/3 & | & 1/3 & 0 & 0 \\ 0 & 1/3 & -1/3 & | & -2/3 & 1 & 0 \\ -2 & 2 & 4 & | & 0 & 0 & 1 \end{bmatrix}$

Step 3: $r_3 := r_3 - (-2)r_1$
$\begin{bmatrix} 1 & -2/3 & -7/3 & | & 1/3 & 0 & 0 \\ 0 & 1/3 & -1/3 & | & -2/3 & 1 & 0 \\ 0 & 2/3 & -2/3 & | & 2/3 & 0 & 1 \end{bmatrix}$

Step 4: $r_2 := 3r_2$
$\begin{bmatrix} 1 & -2/3 & -7/3 & | & 1/3 & 0 & 0 \\ 0 & 1 & -1 & | & -2 & 3 & 0 \\ 0 & 2/3 & -2/3 & | & 2/3 & 0 & 1 \end{bmatrix}$

Step 5: $r_1 := r_1 - (-2/3)r_2$
$\begin{bmatrix} 1 & 0 & -3 & | & -1 & 2 & 0 \\ 0 & 1 & -1 & | & -2 & 3 & 0 \\ 0 & 2/3 & -2/3 & | & 2/3 & 0 & 1 \end{bmatrix}$

Step 6: $r_3 := r_3 - (2/3)r_2$
$\begin{bmatrix} 1 & 0 & -3 & | & -1 & 2 & 0 \\ 0 & 1 & -1 & | & -2 & 3 & 0 \\ 0 & 0 & 0 & | & 2 & -2 & 1 \end{bmatrix}$

**Results:**

a) rank($A$) = 2

b) nullity($A$) = 1

c) det($A$) = 0

d) $A^{-1} = \text{does not exist}$

e) ker($A$) = $\text{span}\left\{\begin{bmatrix} 2 \\ 1 \\ 1 \end{bmatrix}\right\}$

 **Solution**

**Row Operations:**

Step 1: $r_1 := r_1 - (-1)r_2$
$\begin{bmatrix} 1 & 0 & -6 & | & 1 & 1 & 0 \\ 0 & 1 & -1 & | & 0 & 1 & 0 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 2: $r_1 := r_1 - (-6)r_3$
$\begin{bmatrix} 1 & 0 & 0 & | & 1 & 1 & 6 \\ 0 & 1 & -1 & | & 0 & 1 & 0 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 3: $r_2 := r_2 - (-1)r_3$
$\begin{bmatrix} 1 & 0 & 0 & | & 1 & 1 & 6 \\ 0 & 1 & 0 & | & 0 & 1 & 1 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

**Results:**

a) rank($A$) = 3

b) nullity($A$) = 0

c) det($A$) = 0

d) $A^{-1} = \begin{bmatrix} 1 & 0 & 3 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

e) ker($A$) = $\{\mathbf{0}\}$

 **Solution**

**Row Operations:**

Step 1: $r_2 := r_2 - (-2)r_1$
$\begin{bmatrix} 1 & 2 & -1 & | & 1 & 0 & 0 \\ 0 & 3 & 3 & | & 2 & 1 & 0 \\ 0 & 2 & 2 & | & 0 & 0 & 1 \end{bmatrix}$

Step 2: $r_2 := 1/3r_2$
$\begin{bmatrix} 1 & 2 & -1 & | & 1 & 0 & 0 \\ 0 & 1 & 1 & | & 2/3 & 1/3 & 0 \\ 0 & 2 & 2 & | & 0 & 0 & 1 \end{bmatrix}$

Step 3: $r_1 := r_1 - (2)r_2$
$\begin{bmatrix} 1 & 0 & -3 & | & -1/3 & -2/3 & 0 \\ 0 & 1 & 1 & | & 2/3 & 1/3 & 0 \\ 0 & 2 & 2 & | & 0 & 0 & 1 \end{bmatrix}$

Step 4: $r_3 := r_3 - (2)r_2$
$\begin{bmatrix} 1 & 0 & -3 & | & -1/3 & -2/3 & 0 \\ 0 & 1 & 1 & | & 2/3 & 1/3 & 0 \\ 0 & 0 & 0 & | & -4/3 & -2/3 & 1 \end{bmatrix}$

**Results:**

a) rank($A$) = 2

b) nullity($A$) = 1

c) det($A$) = 0

d) $A^{-1} = \text{does not exist}$

e) ker($A$) = $\text{span}\left\{\begin{bmatrix} 1 \\ -1 \\ 1 \end{bmatrix}\right\}$

 **Solution**

**Row Operations:**

Step 1: $r_1 := -1r_1$
$\begin{bmatrix} 1 & 0 & 0 & | & -1 & 0 & 0 \\ 1 & -1 & 0 & | & 0 & 1 & 0 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 2: $r_2 := r_2 - r_1$
$\begin{bmatrix} 1 & 0 & 0 & | & -1 & 0 & 0 \\ 0 & -1 & 0 & | & 1 & 1 & 0 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 3: $r_2 := -1r_2$
$\begin{bmatrix} 1 & 0 & 0 & | & -1 & 0 & 0 \\ 0 & 1 & 0 & | & -1 & -1 & 0 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

**Results:**

a) rank($A$) = 3

b) nullity($A$) = 0

c) det($A$) = 0

d) $A^{-1} = \begin{bmatrix} 1 & 2 & 0 \\ -1 & -1 & -2 \\ 0 & 0 & 1 \end{bmatrix}$

e) ker($A$) = $\{\mathbf{0}\}$

 **Solution**

**Row Operations:**

Step 1: $r_1 := 1/2r_1$
$\begin{bmatrix} 1 & 1/2 & -5 & | & 1/2 & 0 & 0 \\ 1 & 1 & -6 & | & 0 & 1 & 0 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 2: $r_2 := r_2 - r_1$
$\begin{bmatrix} 1 & 1/2 & -5 & | & 1/2 & 0 & 0 \\ 0 & 1/2 & -1 & | & -1/2 & 1 & 0 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 3: $r_2 := 2r_2$
$\begin{bmatrix} 1 & 1/2 & -5 & | & 1/2 & 0 & 0 \\ 0 & 1 & -2 & | & -1 & 2 & 0 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 4: $r_1 := r_1 - (1/2)r_2$
$\begin{bmatrix} 1 & 0 & -4 & | & 1 & -1 & 0 \\ 0 & 1 & -2 & | & -1 & 2 & 0 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 5: $r_1 := r_1 - (-4)r_3$
$\begin{bmatrix} 1 & 0 & 0 & | & 1 & -1 & 4 \\ 0 & 1 & -2 & | & -1 & 2 & 0 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

Step 6: $r_2 := r_2 - (-2)r_3$
$\begin{bmatrix} 1 & 0 & 0 & | & 1 & -1 & 4 \\ 0 & 1 & 0 & | & -1 & 2 & 2 \\ 0 & 0 & 1 & | & 0 & 0 & 1 \end{bmatrix}$

**Results:**

a) rank($A$) = 3

b) nullity($A$) = 0

c) det($A$) = 0

d) $A^{-1} = \begin{bmatrix} 3 & -5 & 2 \\ -1 & 2 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

e) ker($A$) = $\{\mathbf{0}\}$



### RREF

**Solution**

**Elementary Row Operations:**

(1) $r_1 := r_1 + (-1)r_2$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

(2) $r_2 := r_2 + (-1)r_1$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

**Result:**

$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

 **Solution**

**Elementary Row Operations:**

(1) $r_2 := r_2 - (2)r_3$

$\quad \begin{bmatrix} 1 & 0 & 2 \\ 2 & 1 & 4 \\ 4 & 2 & 9 \end{bmatrix}$

(2) $r_3 := r_3 + (-2)r_2$

$\quad \begin{bmatrix} 1 & 0 & 2 \\ 2 & 1 & 4 \\ 0 & 0 & 1 \end{bmatrix}$

(3) $r_2 := r_2 + (-2)r_1$

$\quad \begin{bmatrix} 1 & 0 & 2 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

**Result:**

$\begin{bmatrix} 1 & 0 & 2 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

 **Solution**

**Elementary Row Operations:**

(1) $r_1 := r_1 + (-1)r_3$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

(2) $r_1 := r_1 + (-2)r_3$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

**Result:**

$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

 **Solution**

**Elementary Row Operations:**

(1) $r_2 := r_2 - r_3$

$\quad \begin{bmatrix} 1 & -2 & 0 \\ 0 & 1 & -2 \\ 0 & 1 & -2 \end{bmatrix}$

(2) $r_3 := r_3 + (-1)r_2$

$\quad \begin{bmatrix} 1 & -2 & 0 \\ 0 & 1 & -2 \\ 0 & 0 & 0 \end{bmatrix}$

**Result:**

$\begin{bmatrix} 1 & -2 & 0 \\ 0 & 1 & -2 \\ 0 & 0 & 0 \end{bmatrix}$

 **Solution**

**Elementary Row Operations:**

(1) $r_2 := r_2 + (-1)r_1$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

(2) $r_3 := r_3 + (-1)r_2$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & -1 & 0 \end{bmatrix}$

(3) $r_3 := r_3 - r_2$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

**Result:**

$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$



**Solution**

**Elementary Row Operations:**

(1) $r_1 := r_1 + (-2)r_3$

$\quad \begin{bmatrix} 1 & -1 & 0 \\ -2 & 3 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

(2) $r_2 := r_2 - (2)r_1$

$\quad \begin{bmatrix} 1 & -1 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

(3) $r_1 := r_1 - r_2$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

**Result:**

$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

 **Solution**

**Elementary Row Operations:**

(1) $r_1 := r_1 + (-1)r_3$

$\quad \begin{bmatrix} 1 & 0 & 2 \\ 0 & 1 & -2 \\ 0 & 0 & 1 \end{bmatrix}$

(2) $r_1 := r_1 + (-2)r_3$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & -2 \\ 0 & 0 & 1 \end{bmatrix}$

(3) $r_2 := r_2 - (2)r_3$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

**Result:**

$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

 **Solution**

**Elementary Row Operations:**

(1) $r_3 := r_3 + (-1)r_2$

$\quad \begin{bmatrix} 5 & -8 & 0 \\ 2 & -3 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

(2) $r_1 := r_1 + (-2)r_2$

$\quad \begin{bmatrix} 1 & -2 & 0 \\ 2 & -3 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

(3) $r_2 := r_2 + (-2)r_1$

$\quad \begin{bmatrix} 1 & -2 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

**Result:**

$\begin{bmatrix} 1 & -2 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

 **Solution**

**Elementary Row Operations:**

(1) $r_1 := r_1 - (2)r_2$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ -1 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

(2) $r_2 := r_2 - r_1$

$\quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

**Result:**

$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

 **Solution**

**Elementary Row Operations:**

(1) $r_2 := r_2 - r_3$

$\quad \begin{bmatrix} 1 & 0 & -1 \\ 0 & 1 & 0 \\ -1 & 0 & 1 \end{bmatrix}$

(2) $r_3 := r_3 - r_1$

$\quad \begin{bmatrix} 1 & 0 & -1 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

**Result:**

$\begin{bmatrix} 1 & 0 & -1 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$



## Calculus

### Limit

The limit is: $$1$$ The limit is: $$2$$ The limit is: $$1$$ The limit is: $$-2$$ The limit is: $$1$$

The limit is: $$1$$ The limit is: $$1$$ The limit is: $$104$$ The limit is: $$2$$ The limit is: $$11$$

### Derivative

The derivative is: $$\frac{2 x}{x^{2} + 1} + \frac{1}{x + 1}$$ The derivative is: $$\frac{1}{x}$$ The derivative is: $$2 x e^{x^{2}} + 2 e^{2 x}$$ The derivative is: $$\frac{2 x}{x^{2} + 1} + \frac{1}{x + 1}$$ The derivative is: $$x^{2} e^{x} + 2 x e^{x}$$

The derivative is: $$2 x e^{x^{2}} + 2 e^{2 x}$$ The derivative is: $$e^{x}$$ The derivative is: $$x^{3} e^{x} + 3 x^{2} e^{x}$$ The derivative is: $$- \frac{2 x^{3}}{\left(x^{2} + 1\right)^{2}} + \frac{2 x}{x^{2} + 1}$$ The derivative is: $$\frac{2 x}{x^{2} + 1} + \frac{1}{x + 1}$$

### Integral

The indefinite integral is: $$\frac{x \sqrt{4 - x^{2}}}{2} + 2 \operatorname{asin}{\left(\frac{x}{2} \right)}$$
Definite integral from 2 to 3: $$- \pi + 2 \operatorname{asin}{\left(\frac{3}{2} \right)} + \frac{3 \sqrt{5} i}{2}$$ The indefinite integral is: $$\frac{\sqrt{\pi} \operatorname{erf}{\left(x \right)}}{2}$$
Definite integral from 2 to 5: $$- \frac{\sqrt{\pi} \operatorname{erf}{\left(2 \right)}}{2} + \frac{\sqrt{\pi} \operatorname{erf}{\left(5 \right)}}{2}$$ The indefinite integral is: $$\frac{\sqrt{\pi} \operatorname{erf}{\left(x \right)}}{2}$$
Definite integral from 2 to 2: $$0$$ The indefinite integral is: $$\frac{e^{x} \sin{\left(x \right)}}{2} - \frac{e^{x} \cos{\left(x \right)}}{2}$$
Definite integral from 1 to 3: $$- \frac{e \sin{\left(1 \right)}}{2} + \frac{e \cos{\left(1 \right)}}{2} + \frac{e^{3} \sin{\left(3 \right)}}{2} - \frac{e^{3} \cos{\left(3 \right)}}{2}$$ The indefinite integral is: $$3 \log{\left(x - 3 \right)} - 2 \log{\left(x - 2 \right)}$$
Definite integral from 2 to 3: $$-\infty$$

The indefinite integral is: $$\log{\left(\log{\left(x \right)} \right)}$$
Definite integral from 4 to 4: $$0$$ The indefinite integral is: $$\frac{x^{5}}{5} + \frac{5 x^{4}}{4} + \frac{5 x^{3}}{3} + \frac{x^{2}}{2} + 3 x$$
Definite integral from 1 to 3: $$\frac{3026}{15}$$ The indefinite integral is: $$\frac{x^{4} \log{\left(x \right)}}{4} - \frac{x^{4}}{16}$$
Definite integral from 2 to 4: $$-15 - 4 \log{\left(2 \right)} + 64 \log{\left(4 \right)}$$ The indefinite integral is: $$\operatorname{atan}{\left(x \right)}$$
Definite integral from 3 to 4: $$- \operatorname{atan}{\left(3 \right)} + \operatorname{atan}{\left(4 \right)}$$ The indefinite integral is: $$\frac{x \sqrt{4 - x^{2}}}{2} + 2 \operatorname{asin}{\left(\frac{x}{2} \right)}$$
Definite integral from 4 to 5: $$- 4 \sqrt{3} i + 2 \operatorname{asin}{\left(\frac{5}{2} \right)} - 2 \operatorname{asin}{\left(2 \right)} + \frac{5 \sqrt{21} i}{2}$$

### Partial Derivative

$$\frac{\partial f}{\partial x} = 3 x^{2} y^{2} - 6 x y + 2 y^{3}$$
$$\frac{\partial f}{\partial y} = 2 x^{3} y - 3 x^{2} + 6 x y^{2}$$ $$\frac{\partial^2 f}{\partial x^2} = 6 y^{3} \left(2 x^{2} + y\right)$$ $$\frac{\partial f}{\partial x} = 2 x \left(x + y\right) e^{x^{2} + y^{2}} + e^{x^{2} + y^{2}}$$
$$\frac{\partial f}{\partial y} = 2 y \left(x + y\right) e^{x^{2} + y^{2}} + e^{x^{2} + y^{2}}$$ $$\frac{\partial^2 f}{\partial x \partial y} = 2 y \left(3 x^{2} + 2 y^{2}\right)$$ $$\frac{\partial f}{\partial x} = 2 x \left(x + y\right) e^{x^{2} + y^{2}} + e^{x^{2} + y^{2}}$$
$$\frac{\partial f}{\partial y} = 2 y \left(x + y\right) e^{x^{2} + y^{2}} + e^{x^{2} + y^{2}}$$

$$\frac{\partial f}{\partial x} = 2 x \left(x + y\right) e^{x^{2} + y^{2}} + e^{x^{2} + y^{2}}$$
$$\frac{\partial f}{\partial y} = 2 y \left(x + y\right) e^{x^{2} + y^{2}} + e^{x^{2} + y^{2}}$$ $$\frac{\partial f}{\partial x} = 2 x \left(x + y\right) e^{x^{2} + y^{2}} + e^{x^{2} + y^{2}}$$
$$\frac{\partial f}{\partial y} = 2 y \left(x + y\right) e^{x^{2} + y^{2}} + e^{x^{2} + y^{2}}$$ $$\frac{\partial y}{\partial x} = \frac{- 2 x y - y^{2} + y}{x^{2} + 2 x y - x}$$ $$\frac{\partial f}{\partial x} = 2 x \left(x + y\right) e^{x^{2} + y^{2}} + e^{x^{2} + y^{2}}$$
$$\frac{\partial f}{\partial y} = 2 y \left(x + y\right) e^{x^{2} + y^{2}} + e^{x^{2} + y^{2}}$$ $$\frac{\partial y}{\partial x} = \frac{- 2 x y - y^{2} + y}{x^{2} + 2 x y - x}$$

