name: Generate Math Exercise v1

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC
  workflow_dispatch:      # Manual trigger
    inputs:
      num_problems:
        description: 'Number of problems per section'
        required: true
        default: '10'
        type: number

jobs:
  generate-exercise:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history for exercise counting

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.6.32

    - name: Generate exercise
      run: |
        python main.py
      env:
        NUM_PROBLEMS: ${{ github.event.inputs.num_problems || 10 }}

    - name: Copy _extensions folder
      run: cp -r templates/_extensions output/

    - name: Render Quarto Document
      run: |
        cd output
        for f in *.qmd; do
          quarto render "$f" --to typst
        done

    - name: Commit and push if there are changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        git commit -m "Generate exercise $(date +'%Y-%m-%d')" || exit 0
        git push

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: "v${{ github.run_number }}"
        release_name: "Exercise Release ${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Upload PDFs to Release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        for file in output/*.pdf; do
          echo "Uploading $file..."
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Content-Type: application/pdf" \
            --data-binary @"$file" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=$(basename "$file")"
        done